name: build
on:
  push:
    tags:
      - 'v*.*.*'
    branches:
      - master
  pull_request:
jobs:
  build:
    name: Build
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nuget/setup-nuget@v1
      - run: nuget restore VSSentry.sln
      - uses: microsoft/setup-msbuild@v1.0.2
      - name: Build with MSBuild
        run: msbuild VSSentry.sln -p:Configuration=Release
      - name: VSSentry.vsix
        uses: actions/upload-artifact@v2
        with:
          name: Artifact
          path: |
            ${{ github.workspace }}/bin/Release/VSSentry.vsix
